### PR TITLE
Toggle touched flag on all fields

### LINKED ISSUE #8: Mark all fields touched
When I submit the form and validation is failing I want all validation errors to be shown.
So it would be great to tell the form to mark every field as touched.

### PR DESCRIPTION
**Pull request by blabno**
Fixes #8

### CODE REVIEW

File: packages/core/src/types.js [hunk 1]
```diff
@@ -121,15 +121,17 @@ export type FormComponentProps = {
   parentContext?: FormContextData,
   showValidationBeforeTouched?: boolean,
   conditionalUpdate?: boolean,
-  disabled?: boolean
+  disabled?: boolean,
+  touched?: boolean
```
Comment (draperd) [inline packages/core/src/types.js]: Rather than adding a `touched` prop here, it might be better to just reuse the `showValidationBeforeTouched` prop. When this is set to `false` all the warning messages will be shown immediately even if the field hasn't been given focus.

File: packages/core/src/components/Form.js [hunk 2]
```diff
@@ -39,6 +39,12 @@ const formDisabledStateHasChanged = (
 ) =>
   nextProps.disabled !== undefined && nextProps.disabled !== prevState.disabled;
 
+const formTouchedStateHasChanged = (
+  nextProps: FormComponentProps,
+  prevState: FormComponentState
+) =>
+  nextProps.touched !== prevState.touched;
```
Comment (draperd) [inline packages/core/src/components/Form.js]: If we change this to use `showValidationBeforeTouched` (see comment below) then I think this would be better - but the name of the function might want to change (e.g. `formTouchedBehaviourHasChanged` maybe?)

**Comment by blabno** [comment]
Very good point. On Monday I'll evaluate it against my demo and will get back with feedback.

-------- Original Message --------

**Comment by blabno** [comment]
Seems GitHub is having problems today, cause I've pushed additional commit and sometimes it's displayed and sometimes not.
I had to add `showValidationBeforeTouched` property to the state because the `getDerivedStateFromProps` method does not have access to previous props.

**Comment by blabno** [comment]
Seems GitHub is having problems today, cause I've pushed additional commit and sometimes it's displayed and sometimes not.
I had to add `showValidationBeforeTouched` property to the state because the `getDerivedStateFromProps` method does not have access to previous props.

**Comment by blabno** [comment]
Seems GitHub is having problems today, cause I've pushed additional commit and sometimes it's displayed and sometimes not.
I had to add `showValidationBeforeTouched` property to the state because the `getDerivedStateFromProps` method does not have access to previous props.

**Comment by draperd** [comment]
Sorry for not getting back to you today on this ... I'll hopefully have a chance to look at this tomorrow. I'm happy to merge the code as is, but I'm not sure what you mean by the "reset form" functionality. I want to make sure that I don't merge anything that causes any regressions so I'll check your branch out tomorrow and test it quickly before merging.

**Comment by draperd** [comment]
I've merged this to the code base - I should publish a new release next week

**Comment by blabno** [comment]
@draperd Thank you for merging this.
The "Reset form" functionality was something my code introduced. Basically, it would clear `touched` flag from all fields even if they were manually touched.
That was like a side effect and I do not need it at the moment so I think we're good.
Thank you.
